site_name: 全民瘋AI系列 [Python從零開始]
site_author: 10程式中
site_url: https://andy6804tw.github.io/crazyai-python/
extra_css:
  - 'stylesheets/extra.css'
extra_javascript:
  - javascripts/extra.js
theme:
  logo: assets/logo.png
  name: material
  language: 'zh-TW'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  palette:
    primary: 'light blue'
    accent: 'yellow'
repo_url: https://github.com/andy6804tw/crazyai-python
# use_directory_urls: false
edit_uri: ""
# Copyright
copyright: 'Copyright © 2018 - 2024 10程式中'
nav:
  - '1.環境設定':
    - '1.環境設定/1.環境安裝指南.md'
    - '1.環境設定/1.1.Google Colab介紹.md'
    - '1.環境設定/1.2.Anaconda介紹與安裝.md'
    - '1.環境設定/1.3.Miniconda介紹與安裝.md'
  - '2.基礎語法':
    - '2.變數與基本運算.md'
    - '3.資料型態與轉換.md'
    - '4.條件判斷敘述.md'
    - '5.迴圈.md'
    - '6.串列的基本用法.md'
    - '7.函式.md'
  - '3.進階概念':
    - '8.類別.md'
    - '9.模組.md'
    - '10.錯誤與例外處理.md'
    - '11.產生器.md'
  - '4.常用內建函式庫':
    - '12.隨機數random.md'
    - '13.數學math.md'
    - '14.日期和時間datetime.md'
    - '15.正規表示式re.md'
    - '16.檔案處理os.md'
  - '5.資料處理':
    - '17.Numpy.md'
    - '18.Pandas.md'
    - '19.Matplotlib.md'
  - '6.單元測試':
    - '6.單元測試/6.1pytest 學習指南(基礎篇).md'
    - '6.單元測試/6.2pytest 學習指南(進階篇).md'



markdown_extensions:
  - admonition
  - footnotes
  - codehilite:
      guess_lang: false
  - toc:
      permalink: false
plugins:
  - search
  # - mkpdfs:
  #     design: design/report.css
  #     author: Tsai Yi Lin
  #     # company: "10程式中"
  #     toc_title: Table of contents
  #     output_path: pdf/全民瘋AI系列_探索可解釋人工智慧_v1.1.pdf
